const products = [
    {
      name: "Soul Limited Terracotta",
      image: "img/product/product-1.jpg",
      imagesList: ["img/product/product-1.jpg", "img/product/p-1-detail-1.jpg", "img/product/p-1-detail-2.jpg"],
      type: "hot-sales",
      price: 259,
      oldPrice: 319,
      rating: 0,
      colors: ["default", "black", "grey"],
    },
    {
      name: "Soul Limited V-Neck Green",
      image: "img/product/product-2.jpg",
      imagesList: ["img/product/product-2.jpg", "img/product/p-2-detail-1.jpg", "img/product/p-2-detail-2.jpg"],
      type: "new-arrivals",
      price: 329,
      oldPrice: 389,
      rating: 4,
      colors: ["default", "black", "grey"],
    },
    {
      name: "Soul Limited V-Neck Navy",
      image: "img/product/product-3.jpg",
      imagesList: ["img/product/product-3.jpg", "img/product/p-3-detail-1.jpg", "img/product/p-3-detail-2.jpg"],
      type: "new-arrivals",
      price: 329,
      oldPrice: 389,
      rating: 4,
      colors: ["default", "black", "grey"],
    },
    {
      name: "Soul Limited V-Neck BW",
      image: "img/product/product-4.jpg",
      imagesList: ["img/product/product-4.jpg", "img/product/p-4-detail-1.jpg", "img/product/p-4-detail-2.jpg"],
      type: "new-sales",
      price: 329,
      oldPrice: 389,
      rating: 4,
      colors: ["default", "black", "grey"],
    },
    {
      name: "Soul Limited Outer",
      image: "img/product/product-5.jpg",
      imagesList: ["img/product/product-5.jpg", "img/product/p-5-detail-1.jpg", "img/product/p-5-detail-2.jpg"],
      type: "new-arrivals",
      price: 299,
      oldPrice: 359,
      rating: 4,
      colors: ["default", "black", "grey"],
    },
    {
      name: "Soul Limited Oversized",
      image: "img/product/product-6.jpg",
      imagesList: ["img/product/product-6.jpg", "img/product/p-6-detail-1.jpg", "img/product/p-6-detail-2.jpg"],
      type: "new-sales",
      price: 299,
      oldPrice: 359,
      rating: 4,
      colors: ["default", "black", "grey"],
    },
  ];